# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_card.ipynb.

# %% auto 0
__all__ = ['Card']

# %% ../00_card.ipynb 10
class Card:
    "A playing card, created by passing in `rank` from `ranks` and `suit` from `suits`"
    def __init__(self, 
                 suit:int, # An index into `suits`
                 rank:int # An index into `ranks`
                ):
        self.suit, self.rank = suit, rank
        
    def __str__(self):
        return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__ = __str__
    def __eq__(self, a:"card"):
        return (self.suit, self.rank)==(a.suit,a.rank)
    def __lt__(self,a:"card"):
        return (self.suit, self.rank)<(a.suit,a.rank)
    def __gt__(self,a:"card"):
        return (self.suit, self.rank)>(a.suit,a.rank)

    
        
